### ISSUE TITLE
Typescript error: TS2312: An interface can only extend an object

### ISSUE THREAD

**Issue by montoya332** [scroll-into-view/smooth-scroll-into-view-if-needed#1050]
```
node_modules/smooth-scroll-into-view-if-needed/dist/index.d.ts:32:56 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

32 export declare interface SmoothBehaviorOptions extends Options {
```

 This is because you cannot extend a union type using an interface. You must use type alias:
export type Options = { x: number } | { y: number }
export type SmoothBehaviorOptions = Options & { z: number }

**Comment by mortargrind** [comment]
FYI have a [PR](https://github.com/scroll-into-view/smooth-scroll-into-view-if-needed/pull/1052) for this already

**Comment by mortargrind** [comment]
@stipsan Not sure if it was intentional or not but the last release from yesterday does not have the necessary changes from my PR. I still see 

```
export declare interface SmoothBehaviorOptions extends Options { ... }
```
in `smooth-scroll-into-view-if-needed@2.0.1`
